language: cpp

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq
 - sudo apt-get -qq install boost1.55 
 - sudo apt-get install lua5.1 liblua5.1-dev
 - sudo apt-get -qq install gcc-4.8 g++-4.8

before_script:
 - export CXX="g++-4.8"

script:
  - make -C Build config=release
  - lua acceptance_test/test.lua linux/bin/Release/ris
  - make -C Build config=release
  - ./linux/bin/Release/ris-acceptance-test
